apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        server {
            listen 80;
            location / {
                default_type text/plain;
                return 200 "hello this is dev\n";
            }
        }
    }

